
server:
  port: 8080
  servlet:
    context-path: /gateway

spring:
  application:
    name: gateway

eureka:
  instance:
    hostname: eureka-service-develop.herokuapp.com
  client:
    serviceUrl:
      defaultZone: https://eureka-service-develop.herokuapp.com/eureka

zuul:
  prefix: /api
  ignored-services: "*"

  routes:
    CrudService:
      path: /CrudService/**
      service-id: crud
      strip-prefix: false
      custom-sensitive-headers: true
